apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-deploy
  labels:
    app: banking-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: banking-app
  template:
    metadata:
      labels:
        app: banking-app
    spec:
      containers:
      - name: banking-container
        image: sharikhkhan/bankin_finance:latest
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: banking-np-service
  labels:
    app: banking-app
spec:
  selector:
    app: banking-app

  type: NodePort
  ports:
  - nodePort: 31000
    port: 8081
    targetPort: 8081
